/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 island.gltf 
Author: LukyTechnology (https://sketchfab.com/LukyTechnology)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/lobby-island-ecac2040ddb04047862d96d97e67ae07
Title: Lobby | Island
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Island(props) {
  const { nodes, materials } = useGLTF('/island.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Beacon} color="#ff0000"  />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Block_of_Diamond} color="#ff0000" />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Glass} color="#ff0000" />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Redstone_Torch_active} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Sea_Lantern} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Stationary_Water} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Stationary_Water} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Torch} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Brewing_Stand} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Oak_Planks} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Redstone_Lamp_active} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Oak_Planks_0} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Oak_Planks_0} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Block_of_Quartz} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Block_of_Quartz} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Block_of_Quartz} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Snow_Block} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Snow_Block} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Snow_Block} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Snow_Block} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Snow_Block} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Snow_Block_0} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Stained_Glass_Pane} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Stained_Glass_Pane} />
      </group>
    </group>
  )
}

useGLTF.preload('/island.gltf')
