/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 astroboy.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/astroboy.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="c5124da5117a400780e958aa0f2f5af9fbx">
          <group name="RootNode">
            <group name="Cube" position={[-8.778, 179.843, 49.943]} rotation={[-3.134, -1.42, -1.77]} scale={[248.574, 248.573, 248.573]}>
              <mesh name="Cube_Cubo_2_0" geometry={nodes.Cube_Cubo_2_0.geometry} material={materials['Cubo 2']} />
            </group>
            <group name="Cube001" position={[-8.778, 179.843, 49.943]} rotation={[-3.134, -1.42, -1.77]} scale={248.573}>
              <mesh name="Cube001_Cubo_0" geometry={nodes.Cube001_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Icosphere" position={[581.25, 34.364, 179.605]} rotation={[-1.567, 0, 0]} scale={-83.806}>
              <mesh name="Icosphere_Cubo_0" geometry={nodes.Icosphere_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Sphere" position={[524.397, 68.698, 573.934]} rotation={[-1.568, 0, 0]} scale={-108.832}>
              <mesh name="Sphere_Cubo_0" geometry={nodes.Sphere_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Cone" position={[-1211.88, -499.062, 477.627]} rotation={[-1.914, -0.15, -0.292]} scale={39.664}>
              <mesh name="Cone_Cubo_0" geometry={nodes.Cone_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Cube002" position={[239.255, 1285.23, -243.66]} rotation={[-1.573, -0.001, 0.001]} scale={77.667}>
              <mesh name="Cube002_Cubo_0" geometry={nodes.Cube002_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Torus" position={[494.651, 621.862, 481.051]} rotation={[-0.581, 1.039, -3.11]} scale={[-143.814, -143.815, -143.815]}>
              <mesh name="Torus_Cubo_0" geometry={nodes.Torus_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Cube003" position={[2023.42, 228.055, 51.928]} rotation={[-1.05, 0.86, 2.986]} scale={[-192.363, -192.362, -192.362]}>
              <mesh name="Cube003_Cubo_0" geometry={nodes.Cube003_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Torus001" position={[-224.423, 771.257, -350.097]} rotation={[1.596, 0.294, 1.359]} scale={-80.056}>
              <mesh name="Torus001_Cubo_0" geometry={nodes.Torus001_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Sphere001" position={[402.126, 2442.33, -1644.72]} rotation={[-Math.PI / 2, 0.007, 0]} scale={[-346.369, -346.368, -346.369]}>
              <mesh name="Sphere001_Cubo_0" geometry={nodes.Sphere001_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Icosphere001" position={[-92.343, 1602.56, -469.142]} rotation={[-Math.PI / 2, 0, 0]} scale={55.568}>
              <mesh name="Icosphere001_Cubo_0" geometry={nodes.Icosphere001_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Cone001" position={[-948.593, -365.265, 986.938]} rotation={[-0.562, 1.072, 0.39]} scale={22.75}>
              <mesh name="Cone001_Cubo_0" geometry={nodes.Cone001_Cubo_0.geometry} material={materials.Cubo} />
            </group>
            <group name="Armature" scale={99.966}>
              <group name="Skeleton">
                <primitive object={nodes.mixamorigHips_01} />
              </group>
            </group>
            <group name="Domo" position={[0, 166.388, 57.047]} scale={8094.79}>
              <mesh name="Domo_Techo_0" geometry={nodes.Domo_Techo_0.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_1" geometry={nodes.Domo_Techo_0_1.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_2" geometry={nodes.Domo_Techo_0_2.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_3" geometry={nodes.Domo_Techo_0_3.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_4" geometry={nodes.Domo_Techo_0_4.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_5" geometry={nodes.Domo_Techo_0_5.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_6" geometry={nodes.Domo_Techo_0_6.geometry} material={materials.Techo} />
              <mesh name="Domo_Techo_0_7" geometry={nodes.Domo_Techo_0_7.geometry} material={materials.Techo} />
            </group>
          </group>
        </group>
        <skinnedMesh name="PM3D_Ring3D1_1_Astronauta_1_0" geometry={nodes.PM3D_Ring3D1_1_Astronauta_1_0.geometry} material={materials.Astronauta_1} skeleton={nodes.PM3D_Ring3D1_1_Astronauta_1_0.skeleton} />
        <skinnedMesh name="Broche1_1_Astronauta_1_0" geometry={nodes.Broche1_1_Astronauta_1_0.geometry} material={materials.Astronauta_1} skeleton={nodes.Broche1_1_Astronauta_1_0.skeleton} />
        <skinnedMesh name="Astronauta_1_Astronauta_0" geometry={nodes.Astronauta_1_Astronauta_0.geometry} material={materials.Astronauta} skeleton={nodes.Astronauta_1_Astronauta_0.skeleton} />
        <skinnedMesh name="cintas_1_Astronauta_1_0" geometry={nodes.cintas_1_Astronauta_1_0.geometry} material={materials.Astronauta_1} skeleton={nodes.cintas_1_Astronauta_1_0.skeleton} />
        <skinnedMesh name="Broche2_Astronauta_1_0" geometry={nodes.Broche2_Astronauta_1_0.geometry} material={materials.Astronauta_1} skeleton={nodes.Broche2_Astronauta_1_0.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/astroboy.gltf')
