/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 astronaut.gltf 
Author: Gabriel Gonzalez (https://sketchfab.com/gabrielgonzalezdm)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/floating-astronaut-848c04d21c274b4cba8954816f26dd8a
Title: Floating Astronaut
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/astronaut.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.98, 0.654, -0.736]}>
          <group name="c5124da5117a400780e958aa0f2f5af9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Camera" position={[-1376.125, -885.618, 1044.992]} rotation={[0.825, 0.818, 0]} scale={100}>
                  <group name="Object_121" />
                </group>
                <group name="Cube" position={[-8.778, 179.843, 49.943]} rotation={[-3.134, -1.42, -1.77]} scale={248.573}>
                  <mesh name="Cube_Cubo_2_0" geometry={nodes.Cube_Cubo_2_0.geometry} material={materials.Cubo_2} />
                </group>
                <group name="Cube001" position={[-8.778, 179.843, 49.943]} rotation={[-3.134, -1.42, -1.77]} scale={248.573}>
                  <mesh name="Cube001_Cubo_0" geometry={nodes.Cube001_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Icosphere" position={[581.25, 34.364, 179.605]} rotation={[-1.567, 0, 0]} scale={-83.806}>
                  <mesh name="Icosphere_Cubo_0" geometry={nodes.Icosphere_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Sphere" position={[524.397, 68.698, 573.934]} rotation={[-1.568, 0, 0]} scale={-108.832}>
                  <mesh name="Sphere_Cubo_0" geometry={nodes.Sphere_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Cone" position={[-1211.883, -499.063, 477.627]} rotation={[-1.914, -0.15, -0.292]} scale={39.664}>
                  <mesh name="Cone_Cubo_0" geometry={nodes.Cone_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Cube002" position={[239.255, 1285.232, -243.66]} rotation={[-1.573, -0.001, 0.001]} scale={77.667}>
                  <mesh name="Cube002_Cubo_0" geometry={nodes.Cube002_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Torus" position={[494.651, 621.862, 481.051]} rotation={[-0.581, 1.039, -3.11]} scale={-143.815}>
                  <mesh name="Torus_Cubo_0" geometry={nodes.Torus_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Cube003" position={[2023.425, 228.055, 51.928]} rotation={[-1.05, 0.86, 2.986]} scale={-192.362}>
                  <mesh name="Cube003_Cubo_0" geometry={nodes.Cube003_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Torus001" position={[-224.423, 771.257, -350.097]} rotation={[1.596, 0.294, 1.359]} scale={-80.056}>
                  <mesh name="Torus001_Cubo_0" geometry={nodes.Torus001_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Sphere001" position={[402.126, 2442.332, -1644.718]} rotation={[-Math.PI / 2, 0.007, 0]} scale={-346.368}>
                  <mesh name="Sphere001_Cubo_0" geometry={nodes.Sphere001_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Icosphere001" position={[-92.343, 1602.564, -469.142]} rotation={[-Math.PI / 2, 0, 0]} scale={55.568}>
                  <mesh name="Icosphere001_Cubo_0" geometry={nodes.Icosphere001_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Cone001" position={[-948.593, -365.265, 986.938]} rotation={[-0.562, 1.072, 0.39]} scale={22.75}>
                  <mesh name="Cone001_Cubo_0" geometry={nodes.Cone001_Cubo_0.geometry} material={materials.Cubo} />
                </group>
                <group name="Armature" scale={99.966}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_87" scale={99.966} />
                    <group name="Object_89" scale={99.966} />
                    <group name="Object_91" scale={99.966} />
                    <group name="Object_93" scale={99.966} />
                    <group name="Object_95" scale={99.966} />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.Astronauta_1} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.Astronauta_1} skeleton={nodes.Object_90.skeleton} />
                    <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Astronauta} skeleton={nodes.Object_92.skeleton} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Astronauta_1} skeleton={nodes.Object_94.skeleton} />
                    <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Astronauta_1} skeleton={nodes.Object_96.skeleton} />
                  </group>
                </group>
                <group name="PM3D_Ring3D1_1" scale={99.966} />
                <group name="Broche1_1" scale={99.966} />
                <group name="Astronauta_1" scale={99.966} />
                <group name="cintas_1" scale={99.966} />
                <group name="Broche2" scale={99.966} />
                <group name="Sun" position={[0, -211.063, 252.501]} scale={100}>
                  <group name="Object_103" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_104" />
                  </group>
                </group>
                <group name="Spot" position={[-352.854, -124.771, 172.381]} scale={100}>
                  <group name="Object_106" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_107" />
                  </group>
                </group>
                <group name="Point" position={[424.633, 21.347, 385.108]} scale={100}>
                  <group name="Object_109" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_110" />
                  </group>
                </group>
                <group name="Domo" position={[0, 166.388, 57.047]} scale={8094.791}>
                  <mesh name="Domo_Techo_0" geometry={nodes.Domo_Techo_0.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_1" geometry={nodes.Domo_Techo_0_1.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_2" geometry={nodes.Domo_Techo_0_2.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_3" geometry={nodes.Domo_Techo_0_3.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_4" geometry={nodes.Domo_Techo_0_4.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_5" geometry={nodes.Domo_Techo_0_5.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_6" geometry={nodes.Domo_Techo_0_6.geometry} material={materials.Techo} />
                  <mesh name="Domo_Techo_0_7" geometry={nodes.Domo_Techo_0_7.geometry} material={materials.Techo} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/astronaut.gltf')
