/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 gym.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gym.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[325.556, 1.256, -177.759]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={116.732}>
          <mesh geometry={nodes.Cube022_detail_0.geometry} material={materials.detail} />
          <mesh geometry={nodes.Cube022_posters_0.geometry} material={materials.posters} />
        </group>
        <group position={[325.556, 1.256, -177.759]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={116.732}>
          <mesh geometry={nodes.Cube002_detail_0.geometry} material={materials.detail} />
          <mesh geometry={nodes.Cube002_posters_0.geometry} material={materials.posters} />
        </group>
        <mesh geometry={nodes.Plane005_posters_0.geometry} material={materials.posters} position={[-284.479, 176.224, -589.639]} rotation={[-Math.PI / 2, 0, 0]} scale={114.038} />
        <mesh geometry={nodes.Plane006_posters_0.geometry} material={materials.posters} position={[-386.098, 174.851, -589.639]} rotation={[-Math.PI / 2, 0, 0]} scale={74.976} />
        <mesh geometry={nodes.Plane007_posters_0.geometry} material={materials.posters} position={[228.738, 190.148, -589.639]} rotation={[-Math.PI / 2, 0, 0]} scale={85.939} />
        <mesh geometry={nodes.Plane009_posters_0.geometry} material={materials.posters} position={[-165.457, 162.477, 468.963]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={98.653} />
        <mesh geometry={nodes.Plane010_posters_0.geometry} material={materials.posters} position={[499.157, 189.926, -503.484]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={115.479} />
        <mesh geometry={nodes.Cube019_posters_0.geometry} material={materials.posters} position={[-500.072, 167.269, -12.261]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 118.566]} />
        <mesh geometry={nodes.Cube001_walls_0.geometry} material={materials.walls} position={[0, -3.072, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube017_walls_0.geometry} material={materials.walls} position={[-422.589, -18.319, -206.18]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube018_walls_0.geometry} material={materials.walls} position={[-31.891, -3.072, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube021_walls_0.geometry} material={materials.walls} position={[0, -3.072, -60.053]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.garage_door_walls_0.geometry} material={materials.walls} position={[780.433, 1.347, 37.653]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[60.911, 92.592, 96.938]} />
        <mesh geometry={nodes.Cube009_walls_0.geometry} material={materials.walls} position={[13.652, -4.472, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube023_walls_0.geometry} material={materials.walls} position={[0, -3.072, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder_detail_0.geometry} material={materials.detail} position={[-189.77, -2.111, -357.844]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder001_detail_0.geometry} material={materials.detail} position={[458.26, 3.152, -543.785]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube004_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 338.08]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder005_detail_0.geometry} material={materials.detail} position={[-301.86, 0, 377.965]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube005_detail_0.geometry} material={materials.detail} position={[241.358, 0, 398.385]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder006_detail_0.geometry} material={materials.detail} position={[245.104, 90.566, 399.359]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube007_detail_0.geometry} material={materials.detail} position={[79.364, 0, -550.127]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Cube008_detail_0.geometry} material={materials.detail} position={[-459.098, -8.554, -438.924]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Sphere001_detail_0.geometry} material={materials.detail} position={[401.104, 0, 360.105]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube006_detail_0.geometry} material={materials.detail} position={[310.713, 0, -558.829]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.towelroll006_detail_0.geometry} material={materials.detail} position={[-512.049, 72.79, 173.905]} rotation={[0, 1.567, 2.213]} scale={100} />
        <mesh geometry={nodes.towel01013_detail_0.geometry} material={materials.detail} position={[-512.023, 72.814, 156.17]} rotation={[-Math.PI / 2, 0, 0.829]} scale={100} />
        <mesh geometry={nodes.towel01001_detail_0.geometry} material={materials.detail} position={[-512.023, 72.814, 131.243]} rotation={[-Math.PI / 2, 0, 0.829]} scale={100} />
        <mesh geometry={nodes.towel01002_detail_0.geometry} material={materials.detail} position={[-512.023, 81.464, 156.17]} rotation={[-Math.PI / 2, 0, 0.829]} scale={100} />
        <mesh geometry={nodes.towel01003_detail_0.geometry} material={materials.detail} position={[-512.023, 81.464, 131.243]} rotation={[-Math.PI / 2, 0, 0.829]} scale={100} />
        <mesh geometry={nodes.towel01004_detail_0.geometry} material={materials.detail} position={[-512.023, 90.574, 156.17]} rotation={[-Math.PI / 2, 0, 0.829]} scale={100} />
        <mesh geometry={nodes.Cube011_detail_0.geometry} material={materials.detail} position={[4.528, 0, 361.827]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.BezierCurve001_detail_0.geometry} material={materials.detail} position={[-508.229, 205.391, 305.267]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube020_detail_0.geometry} material={materials.detail} position={[-463.428, 0, -2.264]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube028_detail_0.geometry} material={materials.detail} position={[-405.418, 142.921, 451.825]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={53.665} />
        <mesh geometry={nodes.Cube029_detail_0.geometry} material={materials.detail} position={[-405.418, 140.693, 459.016]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={53.665} />
        <mesh geometry={nodes.Cube030_detail_0.geometry} material={materials.detail} position={[-459.055, -2.809, 12.635]} rotation={[-Math.PI / 2, 0, -2.822]} scale={100} />
        <mesh geometry={nodes.Cylinder015_detail_0.geometry} material={materials.detail} position={[-460.031, 59.038, -26.463]} rotation={[-Math.PI / 2, 0, -0.93]} scale={100} />
        <mesh geometry={nodes.Cylinder016_detail_0.geometry} material={materials.detail} position={[-468.168, 59.038, -56.321]} rotation={[-Math.PI / 2, 0, 2.891]} scale={100} />
        <mesh geometry={nodes.BezierCurve002_detail_0.geometry} material={materials.detail} position={[-532.264, 205.514, 308.107]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.BezierCurve003_detail_0.geometry} material={materials.detail} position={[-521.773, 224.888, 305.107]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.BezierCurve004_detail_0.geometry} material={materials.detail} position={[-523.091, 205.587, 175.709]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.BezierCurve005_detail_0.geometry} material={materials.detail} position={[-441.394, 2.522, 407.432]} rotation={[-Math.PI / 2, 0, 2.264]} scale={100} />
        <mesh geometry={nodes.Cube003_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 298.45]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube010_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 261.624]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={85.31} />
        <mesh geometry={nodes.Cube012_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 226.804]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={85.31} />
        <mesh geometry={nodes.Cube013_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 191.348]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={64.018} />
        <mesh geometry={nodes.Cube014_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 166.073]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={64.018} />
        <mesh geometry={nodes.Cube015_detail_0.geometry} material={materials.detail} position={[-520.892, 0, 140.412]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={64.018} />
        <mesh geometry={nodes.Cylinder002_detail_0.geometry} material={materials.detail} position={[438.438, -2.111, -32.471]} rotation={[-Math.PI / 2, 0, -2.233]} scale={67.017} />
        <mesh geometry={nodes.Cylinder003_detail_0.geometry} material={materials.detail} position={[-522.194, 66.603, 355.889]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={41.908} />
        <mesh geometry={nodes.Cylinder004_detail_0.geometry} material={materials.detail} position={[-522.194, 66.603, 327.18]} rotation={[-Math.PI / 2, 0, -0.626]} scale={41.908} />
        <mesh geometry={nodes.Sphere002_detail_0.geometry} material={materials.detail} position={[-521.565, 135.457, 183.473]} rotation={[-Math.PI / 2, 0, 0]} scale={42.3} />
        <mesh geometry={nodes.Sphere003_detail_0.geometry} material={materials.detail} position={[-521.565, 135.457, 225.659]} rotation={[-Math.PI / 2, 0, 0]} scale={42.3} />
        <mesh geometry={nodes.Sphere004_detail_0.geometry} material={materials.detail} position={[-521.565, 135.457, 139.583]} rotation={[-Math.PI / 2, 0, 0]} scale={33.784} />
        <mesh geometry={nodes.Cylinder007_detail_0.geometry} material={materials.detail} position={[-527.925, 66.683, 207.632]} rotation={[-Math.PI / 2, 0, -0.93]} scale={66.145} />
        <mesh geometry={nodes.Cylinder008_detail_0.geometry} material={materials.detail} position={[-522.673, 66.683, 228.599]} rotation={[-Math.PI / 2, 0, 2.985]} scale={66.145} />
        <mesh geometry={nodes.Sphere005_detail_0.geometry} material={materials.detail} position={[-521.565, 135.457, 333.121]} rotation={[-Math.PI / 2, 0, 0]} scale={61.583} />
        <mesh geometry={nodes.Sphere006_detail_0.geometry} material={materials.detail} position={[-521.565, 135.457, 274.973]} rotation={[-Math.PI / 2, 0, 0]} scale={61.583} />
        <mesh geometry={nodes.Cylinder010_detail_0.geometry} material={materials.detail} position={[455.521, -2.111, -76.883]} rotation={[-Math.PI / 2, 0, -2.641]} scale={67.017} />
        <mesh geometry={nodes.Cylinder012_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -367.88]} rotation={[-1.565, 0.139, 1.555]} scale={74.921} />
        <mesh geometry={nodes.Cylinder013_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -388.136]} rotation={[-1.565, 0.139, 1.555]} scale={74.921} />
        <mesh geometry={nodes.Cylinder014_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -411.547]} rotation={[-1.565, 0.139, 1.555]} scale={74.921} />
        <mesh geometry={nodes.Cylinder017_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -435.316]} rotation={[-1.565, 0.139, 1.555]} scale={[61.906, 74.921, 61.906]} />
        <mesh geometry={nodes.Cylinder018_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -456.772]} rotation={[-1.565, 0.139, 1.555]} scale={[61.906, 74.921, 61.906]} />
        <mesh geometry={nodes.Cylinder019_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -476.381]} rotation={[-1.565, 0.139, 1.555]} scale={[48.277, 74.921, 48.277]} />
        <mesh geometry={nodes.Cylinder020_detail_0.geometry} material={materials.detail} position={[-461.744, 58.047, -491.035]} rotation={[-1.565, 0.139, 1.555]} scale={[48.277, 74.921, 48.277]} />
        <mesh geometry={nodes.Cylinder021_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -367.936]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[40.38, 33.615, 40.38]} />
        <mesh geometry={nodes.Cylinder022_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -394.463]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[40.38, 33.615, 40.38]} />
        <mesh geometry={nodes.Cylinder023_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -421.235]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[31.796, 33.615, 31.796]} />
        <mesh geometry={nodes.Cylinder024_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -445.266]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[31.796, 33.615, 31.796]} />
        <mesh geometry={nodes.Cylinder025_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -463.103]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[23.694, 27.702, 23.694]} />
        <mesh geometry={nodes.Cylinder026_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -479.385]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[23.694, 27.702, 23.694]} />
        <mesh geometry={nodes.Cylinder027_detail_0.geometry} material={materials.detail} position={[-471.565, 87.021, -497.827]} rotation={[-Math.PI / 2, 0.181, Math.PI / 2]} scale={[23.694, 27.702, 23.694]} />
        <mesh geometry={nodes.Cylinder028_detail_0.geometry} material={materials.detail} position={[-455.024, 28.571, -367.88]} rotation={[-1.565, 0.139, 1.555]} scale={74.921} />
        <mesh geometry={nodes.Cylinder029_detail_0.geometry} material={materials.detail} position={[-455.024, 28.571, -388.136]} rotation={[-1.565, 0.139, 1.555]} scale={74.921} />
        <mesh geometry={nodes.Cylinder030_detail_0.geometry} material={materials.detail} position={[-455.024, 28.571, -411.547]} rotation={[-1.565, 0.139, 1.555]} scale={74.921} />
        <mesh geometry={nodes.Cylinder031_detail_0.geometry} material={materials.detail} position={[-455.024, 28.571, -435.316]} rotation={[-1.565, 0.139, 1.555]} scale={[61.906, 74.921, 61.906]} />
      </group>
    </group>
  )
}

useGLTF.preload('/gym.gltf')
