/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 industrial.gltf 
Author: TreDè (https://sketchfab.com/luigi_disilvestre)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/vr-industrial-art-gallery-digital-media-2a41778c24444579aa4449a873f0efd8
Title: VR Industrial Art Gallery & Digital Media
*/

import { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, a } from "@react-spring/three"

export default function Model(props) {
  const { nodes, materials } = useGLTF('/industrial.gltf')
  // const [currentPosition, setCurrentPosition] = useState(false);
  const [hovered, setHover] = useState(false)
  const [cubeNumber, setCubeNumber] = useState(0)
  let animarRoom = {}
  // { rojo , verde, azul}
  const positionInitial = [0, -1.2, -1.33]
  const rotationInitial = [.33 , -Math.PI / -1.1, 0]
  const scaleInitial = .5;

  if(cubeNumber == 0){
    animarRoom = useSpring({
      rotation: rotationInitial,
      position: positionInitial,
      scale: scaleInitial,
    })
  }

  if(cubeNumber == 1){
    animarRoom = useSpring({
      rotation: [0, -Math.PI / -1, 0],
      position: [1.7, -1.5, -3.5],
      scale: .8,
    })
  }

  {/* { rojo , verde, azul} */}
  if(cubeNumber == 2){
    animarRoom = useSpring({
      rotation: [.4, -Math.PI / -.5, 0],
      position: [3, -1.5, 1.5],
      scale: .8,
    })
  }

  if(cubeNumber == 3){
    animarRoom = useSpring({
      rotation: [.5, -Math.PI / -.65 , 0],
      position: [-2, -2, 2.2],
      scale: .8,
    })
  }

  if(cubeNumber == 4){
    animarRoom = useSpring({
      rotation: [.33 , -Math.PI / -1.1, 0],
      position: [0, -1.2, -1.33],
      scale: .5,
    })
  }

  const handleClickCube1 = () => {
    // setCurrentPosition(!currentPosition)
    setCubeNumber(1)
    console.log(cubeNumber)
  }

  const handleClickCube2 = () => {
    setCubeNumber(2)
    console.log(cubeNumber)
  }

  const handleClickCube3 = () => {
    setCubeNumber(3)
    console.log(cubeNumber)
  }

  const handleClickCube4 = () => {
    setCubeNumber(4)
    console.log(cubeNumber)
  }

  return (
    <a.group {...props} dispose={null} rotation={animarRoom.rotation}  position={animarRoom.position} scale={animarRoom.scale}>
      <group position={[0.01, 9.159, -12.201]} rotation={[0.289, 0, 0]} scale={0.065}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Light} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[0.01, 8.292, -9.055]} rotation={[0.289, 0, 0]} scale={0.065}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.Light} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[0.01, 7.45, -0.927]} rotation={[0.003, 0, 0]} scale={0.065}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.Light} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[0.01, 7.476, 2.175]} rotation={[0.004, 0, 0]} scale={0.065}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.Light} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[9.866, 6.991, -4.992]} scale={0.014}>
        <group position={[0.045, -28.169, -93.706]} rotation={[1.838, -0.58, -2.679]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_26.geometry} material={materials.BlackMetal} />
            {/* <mesh geometry={nodes.Object_28_1.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} /> */}
            <mesh geometry={nodes.Object_30.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_24.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.045, -28.169, -246.234]} rotation={[1.992, -0.486, -2.378]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_34.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes.Object_38.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_32.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.045, -28.169, 233.101]} rotation={[1.131, -0.469, 2.336]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_42.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            {/* <mesh geometry={nodes.Object_46_1.geometry} material={materials.Light} position={[0.001, 0.553, 0]} /> */}
          </group>
          <mesh geometry={nodes.Object_40.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.045, -28.169, 61.755]} rotation={[1.37, -0.603, 2.797]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_50.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_52.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes.Object_54.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_48.geometry} material={materials.BlackMetal} />
        </group>
        <mesh geometry={nodes.Object_22.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[-9.85, 6.991, -4.992]} scale={0.014}>
        <group position={[0.41, -28.169, -251.842]} rotation={[1.874, 0.563, -0.53]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_62.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes.Object_66.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_60.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.41, -28.169, -76.647]} rotation={[1.509, 0.629, 0.104]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_70.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_72.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes.Object_74.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_68.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.41, -28.169, 101.301]} rotation={[1.507, 0.629, 0.108]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_78.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_80.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes.Object_82.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_76.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.41, -28.169, 260.162]} rotation={[1.21, 0.531, 0.64]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes.Object_86.geometry} material={materials.BlackMetal} />
            <mesh geometry={nodes.Object_88.geometry} material={materials.Red_Led} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes.Object_90.geometry} material={materials.Light} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes.Object_84.geometry} material={materials.BlackMetal} />
        </group>
        <mesh geometry={nodes.Object_58.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[-0.383, 6.714, -5.855]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[-0.427, -31.979, 233.786]} rotation={[0, 0.692, 0]} scale={1.919}>
          <mesh geometry={nodes.Object_94.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.219, -31.979, 61.171]} rotation={[0, 1.294, 0]} scale={1.919}>
          <mesh geometry={nodes.Object_98.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.25, -31.979, -93.901]} rotation={[-Math.PI, 1.41, -Math.PI]} scale={1.919}>
          <mesh geometry={nodes.Object_102.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.301, -31.979, -246.817]} rotation={[-Math.PI, 0.834, -Math.PI]} scale={1.919}>
          <mesh geometry={nodes.Object_106.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_108.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <mesh geometry={nodes.Object_92.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[7.842, 6.033, -14.865]} rotation={[0.264, 0, 0]} scale={0.194}>
        <mesh geometry={nodes.Object_110.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.Speakers} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[0.02, 6.033, -14.865]} rotation={[0.264, 0, 0]} scale={0.194}>
        <mesh geometry={nodes.Object_114.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.Speakers} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-7.861, 6.033, -14.865]} rotation={[0.264, 0, 0]} scale={0.194}>
        <mesh geometry={nodes.Object_118.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.Speakers} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-8.477, 5.421, 4.893]} rotation={[2.877, 0, Math.PI]} scale={0.194}>
        <mesh geometry={nodes.Object_122.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_124.geometry} material={materials.Speakers} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-0.656, 5.421, 4.893]} rotation={[2.877, 0, Math.PI]} scale={0.194}>
        <mesh geometry={nodes.Object_126.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.Speakers} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[7.225, 5.421, 4.893]} rotation={[2.877, 0, Math.PI]} scale={0.194}>
        <mesh geometry={nodes.Object_130.geometry} material={materials.BlackMetal} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.Speakers} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-0.383, 6.714, -4.046]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[0.456, -31.979, -246.174]} rotation={[-Math.PI, -0.806, -Math.PI]} scale={1.919}>
          <mesh geometry={nodes.Object_136.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.349, -31.979, 233.216]} rotation={[0, -0.767, 0]} scale={1.919}>
          <mesh geometry={nodes.Object_140.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.403, -31.979, 60.256]} rotation={[0, -1.367, 0]} scale={1.919}>
          <mesh geometry={nodes.Object_144.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_146.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.43, -31.979, -92.872]} rotation={[Math.PI, -1.411, Math.PI]} scale={1.919}>
          <mesh geometry={nodes.Object_148.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.Speakers} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <mesh geometry={nodes.Object_134.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[0.3, 0, -4.108]}>
        <group position={[4.651, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_161.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[8.57, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_164.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_165.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[12.507, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_167.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-13.137, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_170.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_171.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-9.219, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_173.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-5.282, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_176.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_177.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[1.646, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_179.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[5.565, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_182.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_183.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[9.502, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_185.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-10.109, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_188.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_189.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-6.19, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_191.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-2.253, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_194.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_195.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-13.365, 4.606, -10.815]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_197.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[13.232, 4.608, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_200.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_201.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[2.395, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_203.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[6.314, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_206.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_207.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[10.251, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_209.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-9.359, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_212.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_213.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-5.441, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_215.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-1.504, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_218.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_219.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-13.265, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_221.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[13.34, 7.647, -10.815]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_224.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_225.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[14.624, 7.65, -8.889]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_227.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[14.624, 7.644, -5.006]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_230.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_231.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[14.624, 7.395, -1.212]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_233.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[14.625, 7.054, 2.852]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_236.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_237.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[14.625, 6.884, 6.731]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_239.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_240.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-2.177, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_242.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_243.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-6.096, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_245.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_246.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-10.033, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_248.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_249.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[9.578, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_251.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_252.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[5.659, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_254.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_255.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[1.722, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_257.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[12.833, 1.546, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_260.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_261.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-13.763, 1.548, 9.059]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_263.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-2.927, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_266.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_267.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-6.845, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_269.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_270.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-10.782, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_272.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_273.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[8.828, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_275.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_276.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[4.909, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_278.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_279.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[0.972, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_281.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_282.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[12.734, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_284.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_285.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-13.871, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_287.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_288.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-15.224, 6.884, 6.731]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_290.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_291.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-15.224, 7.054, 2.852]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_293.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_294.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-15.223, 7.395, -1.212]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_296.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_297.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-15.223, 7.644, -5.006]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_299.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_300.geometry} material={materials.BlackMetal} />
        </group>
        <group position={[-15.223, 7.65, -8.889]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes.Object_302.geometry} material={materials.MetalWire} />
          <mesh geometry={nodes.Object_303.geometry} material={materials.BlackMetal} />
        </group>
      </group>
      <group position={[0, 7.077, 0]}>
        <mesh geometry={nodes.Object_306.geometry} material={materials.Galvanized_Metal} position={[-0.594, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_308.geometry} material={materials.Galvanized_Metal} position={[-14.357, 0.246, -0.709]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.Galvanized_Metal} position={[-14.357, 0.616, -6.715]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_312.geometry} material={materials.Galvanized_Metal} position={[-0.121, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes.Object_314.geometry} material={materials.Galvanized_Metal} position={[3.883, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes.Object_316.geometry} material={materials.Galvanized_Metal} position={[7.887, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes.Object_318.geometry} material={materials.Galvanized_Metal} position={[-4.125, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes.Object_320.geometry} material={materials.Galvanized_Metal} position={[14.357, 0.976, -12.877]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_322.geometry} material={materials.Galvanized_Metal} position={[1.591, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes.Object_324.geometry} material={materials.Galvanized_Metal} position={[5.595, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes.Object_326.geometry} material={materials.Galvanized_Metal} position={[9.599, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes.Object_328.geometry} material={materials.Galvanized_Metal} position={[-10.421, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes.Object_330.geometry} material={materials.Galvanized_Metal} position={[-6.417, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes.Object_332.geometry} material={materials.Galvanized_Metal} position={[-2.413, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes.Object_334.geometry} material={materials.Galvanized_Metal} position={[14.359, 0.202, -2.529]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_336.geometry} material={materials.Galvanized_Metal} position={[14.359, 0.559, -8.534]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_338.geometry} material={materials.Galvanized_Metal} position={[-14.358, 0.202, -2.529]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_340.geometry} material={materials.Galvanized_Metal} position={[-14.358, 0.559, -8.534]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_342.geometry} material={materials.Galvanized_Metal} position={[2.063, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes.Object_344.geometry} material={materials.Galvanized_Metal} position={[6.068, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes.Object_346.geometry} material={materials.Galvanized_Metal} position={[10.071, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes.Object_348.geometry} material={materials.Galvanized_Metal} position={[-5.944, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes.Object_350.geometry} material={materials.Galvanized_Metal} position={[-1.94, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes.Object_352.geometry} material={materials.Galvanized_Metal} position={[-8.218, 2.282, -14.469]} scale={0.154} />
        <mesh geometry={nodes.Object_354.geometry} material={materials.Galvanized_Metal} position={[13.883, -0.078, 3.755]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_356.geometry} material={materials.Galvanized_Metal} position={[-13.885, -0.078, 3.755]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_358.geometry} material={materials.Galvanized_Metal} position={[11.824, 2.217, -14.466]} rotation={[0, 0, -Math.PI]} scale={0.154} />
        <mesh geometry={nodes.Object_360.geometry} material={materials.Galvanized_Metal} position={[12.493, 1.131, -14.474]} scale={0.154} />
        <mesh geometry={nodes.Object_362.geometry} material={materials.Galvanized_Metal} position={[13.348, 0.992, -14.347]} scale={0.154} />
        <mesh geometry={nodes.Object_364.geometry} material={materials.Galvanized_Metal} position={[14.357, 0.176, 1.226]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_366.geometry} material={materials.Galvanized_Metal} position={[-14.36, 0.176, 1.226]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_368.geometry} material={materials.Galvanized_Metal} position={[14.357, 0.605, -4.779]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_370.geometry} material={materials.Galvanized_Metal} position={[14.357, 0.919, -10.785]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_372.geometry} material={materials.Galvanized_Metal} position={[-14.36, 0.605, -4.779]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_374.geometry} material={materials.Galvanized_Metal} position={[-14.36, 0.919, -10.785]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_376.geometry} material={materials.Galvanized_Metal} position={[-13.967, 1.751, -13.905]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_378.geometry} material={materials.Galvanized_Metal} position={[3.41, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_380.geometry} material={materials.Galvanized_Metal} position={[7.414, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_382.geometry} material={materials.Galvanized_Metal} position={[11.418, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_384.geometry} material={materials.Galvanized_Metal} position={[-12.606, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_386.geometry} material={materials.Galvanized_Metal} position={[-8.602, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_388.geometry} material={materials.Galvanized_Metal} position={[-4.598, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes.Object_390.geometry} material={materials.Galvanized_Metal} position={[14.36, 0.246, -0.709]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes.Object_392.geometry} material={materials.Galvanized_Metal} position={[14.36, 0.616, -6.715]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
      </group>
      <group position={[-0.042, 6.254, -5.007]} scale={0.473}>
        <mesh geometry={nodes.Object_395.geometry} material={materials.Galvanized_Metal} position={[0.089, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes.Object_397.geometry} material={materials.Galvanized_Metal} position={[12.756, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes.Object_399.geometry} material={materials.Galvanized_Metal} position={[-12.563, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes.Object_401.geometry} material={materials.Galvanized_Metal} position={[-25.211, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes.Object_403.geometry} material={materials.Galvanized_Metal} position={[25.385, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes.Object_405.geometry} material={materials.Galvanized_Metal} position={[31.366, 0.086, 14.527]} rotation={[0, 1.569, -3.142]} scale={0.384} />
        <mesh geometry={nodes.Object_407.geometry} material={materials.Galvanized_Metal} position={[31.366, 0.086, 19.071]} rotation={[0, 1.569, -3.142]} scale={0.384} />
        <mesh geometry={nodes.Object_409.geometry} material={materials.Galvanized_Metal} position={[26.577, 0.072, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes.Object_411.geometry} material={materials.Galvanized_Metal} position={[9.954, 0.168, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes.Object_413.geometry} material={materials.Galvanized_Metal} position={[-6.624, 0.072, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes.Object_415.geometry} material={materials.Galvanized_Metal} position={[-23.225, 0.222, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes.Object_417.geometry} material={materials.Galvanized_Metal} position={[-30.423, 0.158, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes.Object_419.geometry} material={materials.Galvanized_Metal} position={[30.063, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
      </group>
      <group position={[-14.691, 1.843, 4.306]} scale={0.5}>
        <mesh geometry={nodes.Object_421.geometry} material={materials.Panels} />
        <mesh geometry={nodes.Object_423.geometry} material={materials.Panels} position={[0.249, -0.016, 0.163]} />
      </group>
      <group position={[-15.164, 1.482, 2.64]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_425.geometry} material={materials.Emergency_Door} />
        <mesh geometry={nodes.Object_427.geometry} material={materials.Emergency_Door} position={[-0.027, 0.089, 0.016]} rotation={[0, 0, Math.PI / 2]} scale={[0.113, 0.955, 0.97]} />
      </group>
      <group position={[-3.696, 5.238, 1.723]} rotation={[0, -Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.242, -67.074, -273.637]} rotation={[1.55, 0.545, -1.53]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_433.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_434.geometry} material={materials.Light} />
        </group>
        <group position={[-2.19, -67.074, -144.602]} rotation={[1.315, 0.487, -1.06]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_436.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_437.geometry} material={materials.Light} />
        </group>
        <group position={[-2.389, -67.074, -5.103]} rotation={[1.845, 0.478, -2.119]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_439.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_440.geometry} material={materials.Light} />
        </group>
        <group position={[-2.593, -67.074, 114.369]} rotation={[1.752, 0.517, -1.926]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_442.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_443.geometry} material={materials.Light} />
        </group>
        <group position={[-2.706, -67.074, 273.859]} rotation={[1.5, 0.541, -1.433]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_445.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_446.geometry} material={materials.Light} />
        </group>
        <mesh geometry={nodes.Object_431.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[5.108, 5.238, 1.723]} rotation={[0, -Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.408, -67.074, -240.631]} rotation={[1.959, 0.393, -2.388]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_450.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_451.geometry} material={materials.Light} />
        </group>
        <group position={[-2.408, -67.074, -96.678]} rotation={[1.69, 0.533, -1.803]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_453.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_454.geometry} material={materials.Light} />
        </group>
        <group position={[-2.408, -67.074, 117.125]} rotation={[1.32, 0.49, -1.073]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_456.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_457.geometry} material={materials.Light} />
        </group>
        <group position={[-0.921, -67.074, 2.977]} rotation={[1.473, 0.537, -1.381]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_459.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_460.geometry} material={materials.Light} />
        </group>
        <group position={[-2.099, -67.074, 255.106]} rotation={[1.784, 0.506, -1.992]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_462.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_463.geometry} material={materials.Light} />
        </group>
        <mesh geometry={nodes.Object_448.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[5.196, 5.352, -8.349]}>
        <group position={[-3.787, -1.042, 0.039]} rotation={[2.088, -0.179, 2.838]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_467.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_468.geometry} material={materials.Light} />
        </group>
        <group position={[-0.892, -1.042, 0.027]} rotation={[2.02, 0.319, -2.565]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_470.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_471.geometry} material={materials.Light} />
        </group>
        <group position={[-0.333, -1.042, -0.035]} rotation={[1.038, -0.123, 0.206]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_473.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_474.geometry} material={materials.Light} />
        </group>
        <group position={[1.313, -1.042, 0.013]} rotation={[1.036, 0.113, -0.188]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_476.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_477.geometry} material={materials.Light} />
        </group>
        <group position={[2.77, -1.042, -0.008]} rotation={[1.079, 0.245, -0.425]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_479.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_480.geometry} material={materials.Light} />
        </group>
        <mesh geometry={nodes.Object_465.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[-3.608, 5.352, -8.349]}>
        <group position={[-3.781, -1.042, -0.035]} rotation={[1.098, -0.283, 0.499]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_484.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_485.geometry} material={materials.Light} />
        </group>
        <group position={[-1.452, -1.042, 0.019]} rotation={[2.048, -0.274, 2.66]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_487.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_488.geometry} material={materials.Light} />
        </group>
        <group position={[-1.816, -1.042, -0.035]} rotation={[1.065, 0.212, -0.363]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_490.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_491.geometry} material={materials.Light} />
        </group>
        <group position={[0.446, -1.042, 0.013]} rotation={[2.114, 0.052, -3.055]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_493.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_494.geometry} material={materials.Light} />
        </group>
        <group position={[2.521, -1.042, -0.008]} rotation={[2.096, 0.154, -2.882]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes.Object_496.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_497.geometry} material={materials.Light} />
        </group>
        <mesh geometry={nodes.Object_482.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[-6.64, 5.536, -12.94]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.281, -88.634, -114.464]} rotation={[1.759, 0.515, -1.94]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_501.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_502.geometry} material={materials.Light} />
        </group>
        <group position={[-2.208, -88.634, 116.102]} rotation={[1.299, 0.478, -1.026]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_504.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_505.geometry} material={materials.Light} />
        </group>
        <mesh geometry={nodes.Object_499.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[5.757, 5.536, -12.94]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.281, -88.634, -114.464]} rotation={[1.759, 0.515, -1.94]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_509.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_510.geometry} material={materials.Light} />
        </group>
        <group position={[-2.208, -88.634, 116.102]} rotation={[1.299, 0.478, -1.026]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes.Object_512.geometry} material={materials.BlackMetal} />
          <mesh geometry={nodes.Object_513.geometry} material={materials.Light} />
        </group>
        <mesh geometry={nodes.Object_507.geometry} material={materials.BlackMetal} />
      </group>
      <group position={[5.745, 1.764, -10.385]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_531.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_533.geometry} material={materials.Canva1} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_535.geometry} material={materials.Canva2} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[5.745, 1.764, -1.172]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_537.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_539.geometry} material={materials.Canva4} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_541.geometry} material={materials.Canva3} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-0.411, 1.764, -1.172]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_543.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_545.geometry} material={materials.Canva6} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_547.geometry} material={materials.Canva5} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-6.54, 1.764, -1.172]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_549.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_551.geometry} material={materials.Canva8} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_553.geometry} material={materials.Canva7} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-6.54, 1.764, -10.422]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_555.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_557.geometry} material={materials.Canva10} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_559.geometry} material={materials.Canva9} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-3.62, 1.764, -5.952]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_561.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_563.geometry} material={materials.Canva12} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_565.geometry} material={materials.Canva11} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[2.249, 1.764, -5.952]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_567.geometry} material={materials.CanvaPanel} />
        <mesh geometry={nodes.Object_569.geometry} material={materials.Canva14} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes.Object_571.geometry} material={materials.Canva13} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-13.102, 2.652, -12.876]} scale={3.191}>
        <mesh geometry={nodes.Object_573.geometry} material={materials.Curve_Panel} />
        <mesh geometry={nodes.Object_575.geometry} material={materials.Curve_Screen} position={[-0.001, -0.002, -0.047]} />
      </group>
      <group position={[14.588, 2.307, -14.104]} scale={0.141}>
        <mesh geometry={nodes.Object_589.geometry} material={materials.Red_Led} />
        <mesh geometry={nodes.Object_591.geometry} material={materials.Light} position={[-0.052, 0.043, 0.096]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.363} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Walls} position={[0.199, 3.874, -5.536]} scale={4.985} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Panels} position={[6.26, 3.094, -4.331]} scale={[0.604, 0.923, 1]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Roof} position={[-0.061, 7.918, -4.981]} rotation={[-Math.PI, 0, 0]} scale={[15.339, 15.339, 10.168]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Screen} position={[14.633, 3.867, -5.064]} scale={[0.604, 0.923, 1]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.BlackMetal} position={[3.669, 0.036, -14.843]} scale={0.181} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.BlackMetal} position={[3.13, 0.351, -14.665]} scale={[0.151, 0.214, 0.081]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.BlackMetal} position={[-3.013, 1.377, -14.752]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.045} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.BlackMetal} position={[3.651, 1.045, -14.852]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.067} />
      <mesh geometry={nodes.Object_429.geometry} material={materials.Floor} position={[0, 0.029, -19.842]} scale={[15.339, 15.339, 10.168]} />
      <mesh geometry={nodes.Object_515.geometry} material={materials.material} position={[-3.514, 0.415, 1.603]} rotation={[-Math.PI, 1.336, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_517.geometry} material={materials.Tape} position={[6.454, 0.05, -0.975]} />
      <mesh geometry={nodes.Object_519.geometry} material={materials.material} position={[2.821, 0.415, 1.621]} rotation={[-Math.PI, 1.336, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_521.geometry} material={materials.material} position={[-11.402, 0.415, -2.843]} rotation={[-Math.PI, -0.236, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_523.geometry} material={materials.material} position={[-11.498, 0.415, -8.219]} rotation={[-Math.PI, -0.252, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_525.geometry} material={materials.material} position={[10.566, 0.415, 0.495]} rotation={[-Math.PI, -0.394, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_527.geometry} material={materials.material} position={[10.229, 0.415, -5.012]} rotation={[-Math.PI, -0.233, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_529.geometry} material={materials.material} position={[10.342, 0.415, -10.491]} rotation={[-Math.PI, -0.161, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes.Object_577.geometry} material={materials.Triple_Canva3} position={[-8.234, 3.272, 4.917]} rotation={[0, Math.PI / 2, 0]} scale={0.904} />
      <mesh geometry={nodes.Object_579.geometry} material={materials.Triple_Canva2} position={[-0.006, 3.272, 4.917]} rotation={[0, Math.PI / 2, 0]} scale={0.904} />
      <mesh geometry={nodes.Object_581.geometry} material={materials.Triple_Canva1} position={[8.271, 3.272, 4.917]} rotation={[0, Math.PI / 2, 0]} scale={0.904} />
      <mesh geometry={nodes.Object_583.geometry} material={materials.MetalWire} position={[3.737, 0.111, -14.843]} rotation={[Math.PI / 2, 0, 0]} scale={[0.071, 0.042, 0.071]} />
      <mesh geometry={nodes.Object_585.geometry} material={materials.Floor} position={[0, 0.029, -19.842]} scale={[15.339, 15.339, 10.168]} />
      <mesh geometry={nodes.Object_587.geometry} material={materials.Wires} position={[0.754, 5.67, 0.632]} />
      <mesh geometry={nodes.Object_593.geometry} material={materials.Light} position={[14.582, 2.84, 3.771]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes.Object_595.geometry} material={materials.Light} position={[14.581, 4.135, -13.996]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes.Object_597.geometry} material={materials.Light} position={[14.581, 3.133, -13.927]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes.Object_599.geometry} material={materials.Light} position={[14.581, 4.134, 3.95]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes.Object_601.geometry} material={materials.Light} position={[14.58, 5.269, -13.658]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.368} />
      <mesh geometry={nodes.Object_603.geometry} material={materials.Light} position={[14.58, 5.269, 3.574]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.368} />

      {/* { rojo , verde, azul} */}
      <mesh 
        position={[2.2, 2.15, -6]}  
        scale={2.6} 
        onClick={handleClickCube1} 
        onPointerOver={(event) => setHover(true)}
        onPointerOut={(event) => setHover(false)}>
          <boxGeometry attach="geometry" args={[.5, .5, .5]}  />
          <meshStandardMaterial attach="material" color={hovered ? '#ff00ff' : 'orange'} transparent={true} opacity={.3} />
      </mesh>

      <mesh 
        position={[10, 5, -6]}
        scale={2.6} 
        onClick={handleClickCube2} 
        onPointerOver={(event) => setHover(true)}
        onPointerOut={(event) => setHover(false)}>
          <boxGeometry attach="geometry" args={[.5, .5, .5]}  />
          <meshStandardMaterial attach="material" color={hovered ? '#ff00ff' : 'orange'} transparent={true} opacity={.3} />
      </mesh>

      <mesh 
        position={[3, 4, -3]}
        scale={2.6} 
        onClick={handleClickCube3} 
        onPointerOver={(event) => setHover(true)}
        onPointerOut={(event) => setHover(false)}>
          <boxGeometry attach="geometry" args={[.5, .5, .5]}  />
          <meshStandardMaterial attach="material" color={hovered ? '#ff00ff' : 'orange'} transparent={true} opacity={.3} />
      </mesh>

      <mesh 
        position={[-10, 4, -3]}
        scale={2.6} 
        onClick={handleClickCube4} 
        onPointerOver={(event) => setHover(true)}
        onPointerOut={(event) => setHover(false)}>
          <boxGeometry attach="geometry" args={[.5, .5, .5]}  />
          <meshStandardMaterial attach="material" color={hovered ? '#ff00ff' : 'orange'} transparent={true} opacity={.3} />
      </mesh>

    </a.group>
  )
}

useGLTF.preload('/industrial.gltf')
