/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 mirror2.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/mirror2.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="0167d126e20c463ca331acc4aea7da9afbx">
          <group name="RootNode">
            <group name="Line035" position={[4480.85, -36769.398, 55121.898]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_1" position={[0, -245.927, 38640.301]}>
                <group name="Line035_Material_#28_0">
                  <mesh name="Line035_Material_#28_0_1" geometry={nodes['Line035_Material_#28_0_1'].geometry} material={nodes['Line035_Material_#28_0_1'].material} />
                  <mesh name="Line035_Material_#28_0_2" geometry={nodes['Line035_Material_#28_0_2'].geometry} material={nodes['Line035_Material_#28_0_2'].material} />
                </group>
              </group>
            </group>
            <group name="Line040" position={[4043.75, -36816.602, 55166.199]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_4" position={[0, -1426.59, 38958.699]}>
                <mesh name="Line040_Material_#28_0" geometry={nodes['Line040_Material_#28_0'].geometry} material={nodes['Line040_Material_#28_0'].material} />
              </group>
            </group>
            <group name="Line042" position={[4391.28, -36751.301, 55104.898]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_7" position={[0, -1857.86, 37432.5]}>
                <group name="Line042_Material_#28_0">
                  <mesh name="Line042_Material_#28_0_1" geometry={nodes['Line042_Material_#28_0_1'].geometry} material={nodes['Line042_Material_#28_0_1'].material} />
                  <mesh name="Line042_Material_#28_0_2" geometry={nodes['Line042_Material_#28_0_2'].geometry} material={nodes['Line042_Material_#28_0_2'].material} />
                </group>
              </group>
            </group>
            <group name="Line081" position={[4922.48, -36838, 55126]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_19" position={[0, -232.917, 38291.801]}>
                <mesh name="Line081_Material_#28_0" geometry={nodes['Line081_Material_#28_0'].geometry} material={nodes['Line081_Material_#28_0'].material} />
              </group>
            </group>
            <group name="Line084" position={[4919.77, -36840.5, 55122.301]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_22" position={[0, -1033, 39152.5]}>
                <group name="Line084_Material_#28_0">
                  <mesh name="Line084_Material_#28_0_1" geometry={nodes['Line084_Material_#28_0_1'].geometry} material={nodes['Line084_Material_#28_0_1'].material} />
                  <mesh name="Line084_Material_#28_0_2" geometry={nodes['Line084_Material_#28_0_2'].geometry} material={nodes['Line084_Material_#28_0_2'].material} />
                </group>
              </group>
            </group>
            <group name="Line085" position={[4827.65, -36729.5, 55128.301]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_25" position={[0, -429.539, 38640.199]}>
                <mesh name="Line085_Material_#28_0" geometry={nodes['Line085_Material_#28_0'].geometry} material={nodes['Line085_Material_#28_0'].material} />
              </group>
            </group>
            <group name="Line086" position={[4292.29, -36777.898, 55055]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_28" position={[0, 1262.71, 39245.602]}>
                <group name="Line086_Material_#28_0">
                  <mesh name="Line086_Material_#28_0_1" geometry={nodes['Line086_Material_#28_0_1'].geometry} material={nodes['Line086_Material_#28_0_1'].material} />
                  <mesh name="Line086_Material_#28_0_2" geometry={nodes['Line086_Material_#28_0_2'].geometry} material={nodes['Line086_Material_#28_0_2'].material} />
                </group>
              </group>
            </group>
            <group name="Line088" position={[5309.84, -36911.398, 55081.699]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_31" position={[0, -137.628, 38713.199]}>
                <mesh name="Line088_Material_#28_0" geometry={nodes['Line088_Material_#28_0'].geometry} material={nodes['Line088_Material_#28_0'].material} />
              </group>
            </group>
            <group name="Line089" position={[4545.62, -36742.898, 54999.5]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
              <group name="_gltfNode_34" position={[0, -638.057, 40252.699]}>
                <mesh name="Line089_Material_#28_0" geometry={nodes['Line089_Material_#28_0'].geometry} material={nodes['Line089_Material_#28_0'].material} />
              </group>
            </group>
            <group name="Text008" position={[5293.36, -5.805, 55219.699]} rotation={[0, -Math.PI / 2, 0]}>
              <group name="Text008_Material_#25as_0">
                <mesh name="Text008_Material_#25as_0_1" geometry={nodes['Text008_Material_#25as_0_1'].geometry} material={materials['Material #25as']} />
                <mesh name="Text008_Material_#25as_0_2" geometry={nodes['Text008_Material_#25as_0_2'].geometry} material={materials['Material #25as']} />
              </group>
            </group>
            <group name="Shape002" position={[5293.36, -5.805, 55219.699]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh name="Shape002_Material_#29_0" geometry={nodes['Shape002_Material_#29_0'].geometry} material={nodes['Shape002_Material_#29_0'].material} />
            </group>
            <group name="Object001" position={[5310.81, -5.805, 55219.699]} rotation={[0, -Math.PI / 2, 0]}>
              <group name="Object001_Material_#25as_0">
                <mesh name="Object001_Material_#25as_0_1" geometry={nodes['Object001_Material_#25as_0_1'].geometry} material={materials['Material #25as']} />
                <mesh name="Object001_Material_#25as_0_2" geometry={nodes['Object001_Material_#25as_0_2'].geometry} material={materials['Material #25as']} />
              </group>
            </group>
            <group name="Object002" position={[5293.36, -3433.81, 55220.699]} rotation={[0, -Math.PI / 2, 0]}>
              <group name="_gltfNode_16" position={[-1.063, 3428, -0.001]}>
                <group name="Object002_Material_#27sd_0">
                  <mesh name="Object002_Material_#27sd_0_1" geometry={nodes['Object002_Material_#27sd_0_1'].geometry} material={materials['Material #27sd']} />
                  <mesh name="Object002_Material_#27sd_0_2" geometry={nodes['Object002_Material_#27sd_0_2'].geometry} material={materials['Material #27sd']} />
                </group>
              </group>
            </group>
            <group name="Text010" position={[5303.43, -5.805, 55219.398]} rotation={[0, -Math.PI / 2, 0]}>
              <group name="Text010_Material_#29_0">
                <mesh name="Text010_Material_#29_0_1" geometry={nodes['Text010_Material_#29_0_1'].geometry} material={nodes['Text010_Material_#29_0_1'].material} />
                <mesh name="Text010_Material_#29_0_2" geometry={nodes['Text010_Material_#29_0_2'].geometry} material={nodes['Text010_Material_#29_0_2'].material} />
              </group>
            </group>
            <group name="Line090" position={[5291.75, 1801.8, 55219.301]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh name="Line090_Material_#29_0" geometry={nodes['Line090_Material_#29_0'].geometry} material={nodes['Line090_Material_#29_0'].material} />
            </group>
            <group name="Plane001" position={[14754.1, 1.001, 55196.398]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh name="Plane001_Material_#29dfxc_0" geometry={nodes['Plane001_Material_#29dfxc_0'].geometry} material={materials['Material #29dfxc']} />
            </group>
            <group name="people2_Plane001_group" position={[5950.44, 0, 55434.398]} rotation={[-Math.PI / 2, 0, 0]} scale={14.104}>
              <group name="_gltfNode_43" position={[-320.643, 1062.83, 0]}>
                <mesh name="people2_Plane001_group_Material_#29df_0" geometry={nodes['people2_Plane001_group_Material_#29df_0'].geometry} material={materials['Material #29df']} />
              </group>
            </group>
            <group name="people" position={[7128.96, 800.787, 58720.801]} rotation={[-Math.PI / 2, 0, 0]} scale={1.909}>
              <group name="_gltfNode_46" position={[-179.715, 2334.03, -418.311]}>
                <mesh name="people_Material_#31df_0" geometry={nodes['people_Material_#31df_0'].geometry} material={materials['Material #31df']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mirror2.gltf')
