/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 tienda.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tienda.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 9.159, -12.201]} rotation={[0.289, 0, 0]} scale={0.065}>
        <mesh geometry={nodes._gltfNode_6.geometry} material={nodes._gltfNode_6.material} />
        <mesh geometry={nodes._gltfNode_7.geometry} material={nodes._gltfNode_7.material} />
      </group>
      <group position={[0.01, 8.292, -9.055]} rotation={[0.289, 0, 0]} scale={0.065}>
        <mesh geometry={nodes._gltfNode_9.geometry} material={nodes._gltfNode_9.material} />
        <mesh geometry={nodes._gltfNode_10.geometry} material={nodes._gltfNode_10.material} />
      </group>
      <group position={[0.01, 7.45, -0.927]} rotation={[0.003, 0, 0]} scale={0.065}>
        <mesh geometry={nodes._gltfNode_12.geometry} material={nodes._gltfNode_12.material} />
        <mesh geometry={nodes._gltfNode_13.geometry} material={nodes._gltfNode_13.material} />
      </group>
      <group position={[0.01, 7.476, 2.175]} rotation={[0.004, 0, 0]} scale={0.065}>
        <mesh geometry={nodes._gltfNode_15.geometry} material={nodes._gltfNode_15.material} />
        <mesh geometry={nodes._gltfNode_16.geometry} material={nodes._gltfNode_16.material} />
      </group>
      <group position={[9.866, 6.991, -4.992]} scale={0.014}>
        <group position={[0.045, -28.169, -93.706]} rotation={[1.838, -0.58, -2.679]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_20.geometry} material={nodes._gltfNode_20.material} />
            <mesh geometry={nodes._gltfNode_21.geometry} material={nodes._gltfNode_21.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_23.geometry} material={nodes._gltfNode_23.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_19.geometry} material={nodes._gltfNode_19.material} />
        </group>
        <group position={[0.045, -28.169, -246.234]} rotation={[1.992, -0.486, -2.378]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_28.geometry} material={nodes._gltfNode_28.material} />
            <mesh geometry={nodes._gltfNode_29.geometry} material={nodes._gltfNode_29.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_31.geometry} material={nodes._gltfNode_31.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_27.geometry} material={nodes._gltfNode_27.material} />
        </group>
        <group position={[0.045, -28.169, 233.101]} rotation={[1.131, -0.469, 2.336]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_36.geometry} material={nodes._gltfNode_36.material} />
            <mesh geometry={nodes._gltfNode_37.geometry} material={nodes._gltfNode_37.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_39.geometry} material={nodes._gltfNode_39.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_35.geometry} material={nodes._gltfNode_35.material} />
        </group>
        <group position={[0.045, -28.169, 61.755]} rotation={[1.37, -0.603, 2.797]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_44.geometry} material={nodes._gltfNode_44.material} />
            <mesh geometry={nodes._gltfNode_45.geometry} material={nodes._gltfNode_45.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_47.geometry} material={nodes._gltfNode_47.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_43.geometry} material={nodes._gltfNode_43.material} />
        </group>
        <mesh geometry={nodes._gltfNode_18.geometry} material={nodes._gltfNode_18.material} />
      </group>
      <group position={[-9.85, 6.991, -4.992]} scale={0.014}>
        <group position={[0.41, -28.169, -251.842]} rotation={[1.874, 0.563, -0.53]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_56.geometry} material={nodes._gltfNode_56.material} />
            <mesh geometry={nodes._gltfNode_57.geometry} material={nodes._gltfNode_57.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_59.geometry} material={nodes._gltfNode_59.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_55.geometry} material={nodes._gltfNode_55.material} />
        </group>
        <group position={[0.41, -28.169, -76.647]} rotation={[1.509, 0.629, 0.104]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_64.geometry} material={nodes._gltfNode_64.material} />
            <mesh geometry={nodes._gltfNode_65.geometry} material={nodes._gltfNode_65.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_67.geometry} material={nodes._gltfNode_67.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_63.geometry} material={nodes._gltfNode_63.material} />
        </group>
        <group position={[0.41, -28.169, 101.301]} rotation={[1.507, 0.629, 0.108]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_72.geometry} material={nodes._gltfNode_72.material} />
            <mesh geometry={nodes._gltfNode_73.geometry} material={nodes._gltfNode_73.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_75.geometry} material={nodes._gltfNode_75.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_71.geometry} material={nodes._gltfNode_71.material} />
        </group>
        <group position={[0.41, -28.169, 260.162]} rotation={[1.21, 0.531, 0.64]} scale={1.372}>
          <group position={[-5.529, 0.03, 11.193]} rotation={[-Math.PI / 2, 0, -2.54]} scale={6.489}>
            <mesh geometry={nodes._gltfNode_80.geometry} material={nodes._gltfNode_80.material} />
            <mesh geometry={nodes._gltfNode_81.geometry} material={nodes._gltfNode_81.material} position={[-0.053, -1.314, -1.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.075} />
            <mesh geometry={nodes._gltfNode_83.geometry} material={nodes._gltfNode_83.material} position={[0.001, 0.553, 0]} />
          </group>
          <mesh geometry={nodes._gltfNode_79.geometry} material={nodes._gltfNode_79.material} />
        </group>
        <mesh geometry={nodes._gltfNode_54.geometry} material={nodes._gltfNode_54.material} />
      </group>
      <group position={[-0.383, 6.714, -5.855]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[-0.427, -31.979, 233.786]} rotation={[0, 0.692, 0]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_89.geometry} material={nodes._gltfNode_89.material} />
          <mesh geometry={nodes._gltfNode_90.geometry} material={nodes._gltfNode_90.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.219, -31.979, 61.171]} rotation={[0, 1.294, 0]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_93.geometry} material={nodes._gltfNode_93.material} />
          <mesh geometry={nodes._gltfNode_94.geometry} material={nodes._gltfNode_94.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.25, -31.979, -93.901]} rotation={[-Math.PI, 1.41, -Math.PI]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_97.geometry} material={nodes._gltfNode_97.material} />
          <mesh geometry={nodes._gltfNode_98.geometry} material={nodes._gltfNode_98.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.301, -31.979, -246.817]} rotation={[-Math.PI, 0.834, -Math.PI]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_101.geometry} material={nodes._gltfNode_101.material} />
          <mesh geometry={nodes._gltfNode_102.geometry} material={nodes._gltfNode_102.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <mesh geometry={nodes._gltfNode_88.geometry} material={nodes._gltfNode_88.material} />
      </group>
      <group position={[7.842, 6.033, -14.865]} rotation={[0.264, 0, 0]} scale={0.194}>
        <mesh geometry={nodes._gltfNode_106.geometry} material={nodes._gltfNode_106.material} />
        <mesh geometry={nodes._gltfNode_107.geometry} material={nodes._gltfNode_107.material} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[0.02, 6.033, -14.865]} rotation={[0.264, 0, 0]} scale={0.194}>
        <mesh geometry={nodes._gltfNode_110.geometry} material={nodes._gltfNode_110.material} />
        <mesh geometry={nodes._gltfNode_111.geometry} material={nodes._gltfNode_111.material} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-7.861, 6.033, -14.865]} rotation={[0.264, 0, 0]} scale={0.194}>
        <mesh geometry={nodes._gltfNode_114.geometry} material={nodes._gltfNode_114.material} />
        <mesh geometry={nodes._gltfNode_115.geometry} material={nodes._gltfNode_115.material} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-8.477, 5.421, 4.893]} rotation={[2.877, 0, Math.PI]} scale={0.194}>
        <mesh geometry={nodes._gltfNode_118.geometry} material={nodes._gltfNode_118.material} />
        <mesh geometry={nodes._gltfNode_119.geometry} material={nodes._gltfNode_119.material} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-0.656, 5.421, 4.893]} rotation={[2.877, 0, Math.PI]} scale={0.194}>
        <mesh geometry={nodes._gltfNode_122.geometry} material={nodes._gltfNode_122.material} />
        <mesh geometry={nodes._gltfNode_123.geometry} material={nodes._gltfNode_123.material} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[7.225, 5.421, 4.893]} rotation={[2.877, 0, Math.PI]} scale={0.194}>
        <mesh geometry={nodes._gltfNode_126.geometry} material={nodes._gltfNode_126.material} />
        <mesh geometry={nodes._gltfNode_127.geometry} material={nodes._gltfNode_127.material} position={[-0.006, 1.932, 1.881]} rotation={[-0.003, 0, 0]} />
      </group>
      <group position={[-0.383, 6.714, -4.046]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[0.456, -31.979, -246.174]} rotation={[-Math.PI, -0.806, -Math.PI]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_131.geometry} material={nodes._gltfNode_131.material} />
          <mesh geometry={nodes._gltfNode_132.geometry} material={nodes._gltfNode_132.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.349, -31.979, 233.216]} rotation={[0, -0.767, 0]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_135.geometry} material={nodes._gltfNode_135.material} />
          <mesh geometry={nodes._gltfNode_136.geometry} material={nodes._gltfNode_136.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.403, -31.979, 60.256]} rotation={[0, -1.367, 0]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_139.geometry} material={nodes._gltfNode_139.material} />
          <mesh geometry={nodes._gltfNode_140.geometry} material={nodes._gltfNode_140.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <group position={[0.43, -31.979, -92.872]} rotation={[Math.PI, -1.411, Math.PI]} scale={1.919}>
          <mesh geometry={nodes._gltfNode_143.geometry} material={nodes._gltfNode_143.material} />
          <mesh geometry={nodes._gltfNode_144.geometry} material={nodes._gltfNode_144.material} position={[-0.006, -16.492, 5.988]} rotation={[0.565, 0, 0]} scale={8.728} />
        </group>
        <mesh geometry={nodes._gltfNode_130.geometry} material={nodes._gltfNode_130.material} />
      </group>
      <group position={[0.3, 0, -4.108]}>
        <group position={[4.651, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_156.geometry} material={nodes._gltfNode_156.material} />
          <mesh geometry={nodes._gltfNode_157.geometry} material={nodes._gltfNode_157.material} />
        </group>
        <group position={[8.57, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_159.geometry} material={nodes._gltfNode_159.material} />
          <mesh geometry={nodes._gltfNode_160.geometry} material={nodes._gltfNode_160.material} />
        </group>
        <group position={[12.507, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_162.geometry} material={nodes._gltfNode_162.material} />
          <mesh geometry={nodes._gltfNode_163.geometry} material={nodes._gltfNode_163.material} />
        </group>
        <group position={[-13.137, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_165.geometry} material={nodes._gltfNode_165.material} />
          <mesh geometry={nodes._gltfNode_166.geometry} material={nodes._gltfNode_166.material} />
        </group>
        <group position={[-9.219, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_168.geometry} material={nodes._gltfNode_168.material} />
          <mesh geometry={nodes._gltfNode_169.geometry} material={nodes._gltfNode_169.material} />
        </group>
        <group position={[-5.282, 1.546, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_171.geometry} material={nodes._gltfNode_171.material} />
          <mesh geometry={nodes._gltfNode_172.geometry} material={nodes._gltfNode_172.material} />
        </group>
        <group position={[1.646, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_174.geometry} material={nodes._gltfNode_174.material} />
          <mesh geometry={nodes._gltfNode_175.geometry} material={nodes._gltfNode_175.material} />
        </group>
        <group position={[5.565, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_177.geometry} material={nodes._gltfNode_177.material} />
          <mesh geometry={nodes._gltfNode_178.geometry} material={nodes._gltfNode_178.material} />
        </group>
        <group position={[9.502, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_180.geometry} material={nodes._gltfNode_180.material} />
          <mesh geometry={nodes._gltfNode_181.geometry} material={nodes._gltfNode_181.material} />
        </group>
        <group position={[-10.109, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_183.geometry} material={nodes._gltfNode_183.material} />
          <mesh geometry={nodes._gltfNode_184.geometry} material={nodes._gltfNode_184.material} />
        </group>
        <group position={[-6.19, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_186.geometry} material={nodes._gltfNode_186.material} />
          <mesh geometry={nodes._gltfNode_187.geometry} material={nodes._gltfNode_187.material} />
        </group>
        <group position={[-2.253, 4.606, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_189.geometry} material={nodes._gltfNode_189.material} />
          <mesh geometry={nodes._gltfNode_190.geometry} material={nodes._gltfNode_190.material} />
        </group>
        <group position={[-13.365, 4.606, -10.815]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_192.geometry} material={nodes._gltfNode_192.material} />
          <mesh geometry={nodes._gltfNode_193.geometry} material={nodes._gltfNode_193.material} />
        </group>
        <group position={[13.232, 4.608, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_195.geometry} material={nodes._gltfNode_195.material} />
          <mesh geometry={nodes._gltfNode_196.geometry} material={nodes._gltfNode_196.material} />
        </group>
        <group position={[2.395, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_198.geometry} material={nodes._gltfNode_198.material} />
          <mesh geometry={nodes._gltfNode_199.geometry} material={nodes._gltfNode_199.material} />
        </group>
        <group position={[6.314, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_201.geometry} material={nodes._gltfNode_201.material} />
          <mesh geometry={nodes._gltfNode_202.geometry} material={nodes._gltfNode_202.material} />
        </group>
        <group position={[10.251, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_204.geometry} material={nodes._gltfNode_204.material} />
          <mesh geometry={nodes._gltfNode_205.geometry} material={nodes._gltfNode_205.material} />
        </group>
        <group position={[-9.359, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_207.geometry} material={nodes._gltfNode_207.material} />
          <mesh geometry={nodes._gltfNode_208.geometry} material={nodes._gltfNode_208.material} />
        </group>
        <group position={[-5.441, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_210.geometry} material={nodes._gltfNode_210.material} />
          <mesh geometry={nodes._gltfNode_211.geometry} material={nodes._gltfNode_211.material} />
        </group>
        <group position={[-1.504, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_213.geometry} material={nodes._gltfNode_213.material} />
          <mesh geometry={nodes._gltfNode_214.geometry} material={nodes._gltfNode_214.material} />
        </group>
        <group position={[-13.265, 7.646, -10.814]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_216.geometry} material={nodes._gltfNode_216.material} />
          <mesh geometry={nodes._gltfNode_217.geometry} material={nodes._gltfNode_217.material} />
        </group>
        <group position={[13.34, 7.647, -10.815]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_219.geometry} material={nodes._gltfNode_219.material} />
          <mesh geometry={nodes._gltfNode_220.geometry} material={nodes._gltfNode_220.material} />
        </group>
        <group position={[14.624, 7.65, -8.889]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_222.geometry} material={nodes._gltfNode_222.material} />
          <mesh geometry={nodes._gltfNode_223.geometry} material={nodes._gltfNode_223.material} />
        </group>
        <group position={[14.624, 7.644, -5.006]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_225.geometry} material={nodes._gltfNode_225.material} />
          <mesh geometry={nodes._gltfNode_226.geometry} material={nodes._gltfNode_226.material} />
        </group>
        <group position={[14.624, 7.395, -1.212]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_228.geometry} material={nodes._gltfNode_228.material} />
          <mesh geometry={nodes._gltfNode_229.geometry} material={nodes._gltfNode_229.material} />
        </group>
        <group position={[14.625, 7.054, 2.852]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_231.geometry} material={nodes._gltfNode_231.material} />
          <mesh geometry={nodes._gltfNode_232.geometry} material={nodes._gltfNode_232.material} />
        </group>
        <group position={[14.625, 6.884, 6.731]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_234.geometry} material={nodes._gltfNode_234.material} />
          <mesh geometry={nodes._gltfNode_235.geometry} material={nodes._gltfNode_235.material} />
        </group>
        <group position={[-2.177, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_237.geometry} material={nodes._gltfNode_237.material} />
          <mesh geometry={nodes._gltfNode_238.geometry} material={nodes._gltfNode_238.material} />
        </group>
        <group position={[-6.096, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_240.geometry} material={nodes._gltfNode_240.material} />
          <mesh geometry={nodes._gltfNode_241.geometry} material={nodes._gltfNode_241.material} />
        </group>
        <group position={[-10.033, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_243.geometry} material={nodes._gltfNode_243.material} />
          <mesh geometry={nodes._gltfNode_244.geometry} material={nodes._gltfNode_244.material} />
        </group>
        <group position={[9.578, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_246.geometry} material={nodes._gltfNode_246.material} />
          <mesh geometry={nodes._gltfNode_247.geometry} material={nodes._gltfNode_247.material} />
        </group>
        <group position={[5.659, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_249.geometry} material={nodes._gltfNode_249.material} />
          <mesh geometry={nodes._gltfNode_250.geometry} material={nodes._gltfNode_250.material} />
        </group>
        <group position={[1.722, 1.547, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_252.geometry} material={nodes._gltfNode_252.material} />
          <mesh geometry={nodes._gltfNode_253.geometry} material={nodes._gltfNode_253.material} />
        </group>
        <group position={[12.833, 1.546, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_255.geometry} material={nodes._gltfNode_255.material} />
          <mesh geometry={nodes._gltfNode_256.geometry} material={nodes._gltfNode_256.material} />
        </group>
        <group position={[-13.763, 1.548, 9.059]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_258.geometry} material={nodes._gltfNode_258.material} />
          <mesh geometry={nodes._gltfNode_259.geometry} material={nodes._gltfNode_259.material} />
        </group>
        <group position={[-2.927, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_261.geometry} material={nodes._gltfNode_261.material} />
          <mesh geometry={nodes._gltfNode_262.geometry} material={nodes._gltfNode_262.material} />
        </group>
        <group position={[-6.845, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_264.geometry} material={nodes._gltfNode_264.material} />
          <mesh geometry={nodes._gltfNode_265.geometry} material={nodes._gltfNode_265.material} />
        </group>
        <group position={[-10.782, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_267.geometry} material={nodes._gltfNode_267.material} />
          <mesh geometry={nodes._gltfNode_268.geometry} material={nodes._gltfNode_268.material} />
        </group>
        <group position={[8.828, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_270.geometry} material={nodes._gltfNode_270.material} />
          <mesh geometry={nodes._gltfNode_271.geometry} material={nodes._gltfNode_271.material} />
        </group>
        <group position={[4.909, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_273.geometry} material={nodes._gltfNode_273.material} />
          <mesh geometry={nodes._gltfNode_274.geometry} material={nodes._gltfNode_274.material} />
        </group>
        <group position={[0.972, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_276.geometry} material={nodes._gltfNode_276.material} />
          <mesh geometry={nodes._gltfNode_277.geometry} material={nodes._gltfNode_277.material} />
        </group>
        <group position={[12.734, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_279.geometry} material={nodes._gltfNode_279.material} />
          <mesh geometry={nodes._gltfNode_280.geometry} material={nodes._gltfNode_280.material} />
        </group>
        <group position={[-13.871, 4.587, 9.06]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_282.geometry} material={nodes._gltfNode_282.material} />
          <mesh geometry={nodes._gltfNode_283.geometry} material={nodes._gltfNode_283.material} />
        </group>
        <group position={[-15.224, 6.884, 6.731]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_285.geometry} material={nodes._gltfNode_285.material} />
          <mesh geometry={nodes._gltfNode_286.geometry} material={nodes._gltfNode_286.material} />
        </group>
        <group position={[-15.224, 7.054, 2.852]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_288.geometry} material={nodes._gltfNode_288.material} />
          <mesh geometry={nodes._gltfNode_289.geometry} material={nodes._gltfNode_289.material} />
        </group>
        <group position={[-15.223, 7.395, -1.212]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_291.geometry} material={nodes._gltfNode_291.material} />
          <mesh geometry={nodes._gltfNode_292.geometry} material={nodes._gltfNode_292.material} />
        </group>
        <group position={[-15.223, 7.644, -5.006]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_294.geometry} material={nodes._gltfNode_294.material} />
          <mesh geometry={nodes._gltfNode_295.geometry} material={nodes._gltfNode_295.material} />
        </group>
        <group position={[-15.223, 7.65, -8.889]} rotation={[0, 0, Math.PI / 2]} scale={[0.008, 1, 1.469]}>
          <mesh geometry={nodes._gltfNode_297.geometry} material={nodes._gltfNode_297.material} />
          <mesh geometry={nodes._gltfNode_298.geometry} material={nodes._gltfNode_298.material} />
        </group>
      </group>
      <group position={[0, 7.077, 0]}>
        <mesh geometry={nodes._gltfNode_301.geometry} material={nodes._gltfNode_301.material} position={[-0.594, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_303.geometry} material={nodes._gltfNode_303.material} position={[-14.357, 0.246, -0.709]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_305.geometry} material={nodes._gltfNode_305.material} position={[-14.357, 0.616, -6.715]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_307.geometry} material={nodes._gltfNode_307.material} position={[-0.121, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_309.geometry} material={nodes._gltfNode_309.material} position={[3.883, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_311.geometry} material={nodes._gltfNode_311.material} position={[7.887, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_313.geometry} material={nodes._gltfNode_313.material} position={[-4.125, 2.268, -14.466]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_315.geometry} material={nodes._gltfNode_315.material} position={[14.357, 0.976, -12.877]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_317.geometry} material={nodes._gltfNode_317.material} position={[1.591, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_319.geometry} material={nodes._gltfNode_319.material} position={[5.595, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_321.geometry} material={nodes._gltfNode_321.material} position={[9.599, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_323.geometry} material={nodes._gltfNode_323.material} position={[-10.421, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_325.geometry} material={nodes._gltfNode_325.material} position={[-6.417, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_327.geometry} material={nodes._gltfNode_327.material} position={[-2.413, -0.166, 4.229]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_329.geometry} material={nodes._gltfNode_329.material} position={[14.359, 0.202, -2.529]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_331.geometry} material={nodes._gltfNode_331.material} position={[14.359, 0.559, -8.534]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_333.geometry} material={nodes._gltfNode_333.material} position={[-14.358, 0.202, -2.529]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_335.geometry} material={nodes._gltfNode_335.material} position={[-14.358, 0.559, -8.534]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_337.geometry} material={nodes._gltfNode_337.material} position={[2.063, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_339.geometry} material={nodes._gltfNode_339.material} position={[6.068, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_341.geometry} material={nodes._gltfNode_341.material} position={[10.071, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_343.geometry} material={nodes._gltfNode_343.material} position={[-5.944, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_345.geometry} material={nodes._gltfNode_345.material} position={[-1.94, 2.243, -14.465]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_347.geometry} material={nodes._gltfNode_347.material} position={[-8.218, 2.282, -14.469]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_349.geometry} material={nodes._gltfNode_349.material} position={[13.883, -0.078, 3.755]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_351.geometry} material={nodes._gltfNode_351.material} position={[-13.885, -0.078, 3.755]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_353.geometry} material={nodes._gltfNode_353.material} position={[11.824, 2.217, -14.466]} rotation={[0, 0, -Math.PI]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_355.geometry} material={nodes._gltfNode_355.material} position={[12.493, 1.132, -14.474]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_357.geometry} material={nodes._gltfNode_357.material} position={[13.347, 0.992, -14.347]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_359.geometry} material={nodes._gltfNode_359.material} position={[14.358, 0.176, 1.226]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_361.geometry} material={nodes._gltfNode_361.material} position={[-14.36, 0.176, 1.226]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_363.geometry} material={nodes._gltfNode_363.material} position={[14.358, 0.605, -4.779]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_365.geometry} material={nodes._gltfNode_365.material} position={[14.358, 0.919, -10.785]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_367.geometry} material={nodes._gltfNode_367.material} position={[-14.36, 0.605, -4.779]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_369.geometry} material={nodes._gltfNode_369.material} position={[-14.36, 0.919, -10.785]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_371.geometry} material={nodes._gltfNode_371.material} position={[-13.967, 1.751, -13.905]} rotation={[0, Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_373.geometry} material={nodes._gltfNode_373.material} position={[3.41, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_375.geometry} material={nodes._gltfNode_375.material} position={[7.414, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_377.geometry} material={nodes._gltfNode_377.material} position={[11.418, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_379.geometry} material={nodes._gltfNode_379.material} position={[-12.606, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_381.geometry} material={nodes._gltfNode_381.material} position={[-8.601, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_383.geometry} material={nodes._gltfNode_383.material} position={[-4.598, -0.14, 4.228]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_385.geometry} material={nodes._gltfNode_385.material} position={[14.36, 0.246, -0.709]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
        <mesh geometry={nodes._gltfNode_387.geometry} material={nodes._gltfNode_387.material} position={[14.36, 0.616, -6.715]} rotation={[0, -Math.PI / 2, 0]} scale={0.154} />
      </group>
      <group position={[-0.042, 6.254, -5.007]} scale={0.473}>
        <mesh geometry={nodes._gltfNode_390.geometry} material={nodes._gltfNode_390.material} position={[0.089, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_392.geometry} material={nodes._gltfNode_392.material} position={[12.756, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_394.geometry} material={nodes._gltfNode_394.material} position={[-12.563, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_396.geometry} material={nodes._gltfNode_396.material} position={[-25.211, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_398.geometry} material={nodes._gltfNode_398.material} position={[25.385, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_400.geometry} material={nodes._gltfNode_400.material} position={[31.366, 0.086, 14.527]} rotation={[0, 1.569, -3.142]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_402.geometry} material={nodes._gltfNode_402.material} position={[31.366, 0.086, 19.071]} rotation={[0, 1.569, -3.142]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_404.geometry} material={nodes._gltfNode_404.material} position={[26.577, 0.072, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_406.geometry} material={nodes._gltfNode_406.material} position={[9.954, 0.168, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_408.geometry} material={nodes._gltfNode_408.material} position={[-6.624, 0.072, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_410.geometry} material={nodes._gltfNode_410.material} position={[-23.225, 0.222, -20.696]} rotation={[-Math.PI, 0.002, 0]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_412.geometry} material={nodes._gltfNode_412.material} position={[-30.424, 0.158, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
        <mesh geometry={nodes._gltfNode_414.geometry} material={nodes._gltfNode_414.material} position={[30.063, 0.086, 20.796]} rotation={[0, 0, -Math.PI]} scale={0.384} />
      </group>
      <group position={[-14.691, 1.843, 4.306]} scale={0.5}>
        <mesh geometry={nodes._gltfNode_417.geometry} material={nodes._gltfNode_417.material} />
        <mesh geometry={nodes._gltfNode_418.geometry} material={nodes._gltfNode_418.material} position={[0.249, -0.016, 0.163]} />
      </group>
      <group position={[-15.164, 1.482, 2.64]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes._gltfNode_421.geometry} material={nodes._gltfNode_421.material} />
        <mesh geometry={nodes._gltfNode_422.geometry} material={nodes._gltfNode_422.material} position={[-0.027, 0.089, 0.016]} rotation={[0, 0, Math.PI / 2]} scale={[0.113, 0.955, 0.97]} />
      </group>
      <group position={[-3.696, 5.238, 1.723]} rotation={[0, -Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.242, -67.074, -273.637]} rotation={[1.55, 0.545, -1.53]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_428.geometry} material={nodes._gltfNode_428.material} />
          <mesh geometry={nodes._gltfNode_429.geometry} material={nodes._gltfNode_429.material} />
        </group>
        <group position={[-2.19, -67.074, -144.602]} rotation={[1.315, 0.487, -1.06]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_431.geometry} material={nodes._gltfNode_431.material} />
          <mesh geometry={nodes._gltfNode_432.geometry} material={nodes._gltfNode_432.material} />
        </group>
        <group position={[-2.389, -67.074, -5.103]} rotation={[1.845, 0.478, -2.119]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_434.geometry} material={nodes._gltfNode_434.material} />
          <mesh geometry={nodes._gltfNode_435.geometry} material={nodes._gltfNode_435.material} />
        </group>
        <group position={[-2.593, -67.074, 114.369]} rotation={[1.752, 0.517, -1.926]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_437.geometry} material={nodes._gltfNode_437.material} />
          <mesh geometry={nodes._gltfNode_438.geometry} material={nodes._gltfNode_438.material} />
        </group>
        <group position={[-2.706, -67.074, 273.859]} rotation={[1.5, 0.541, -1.433]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_440.geometry} material={nodes._gltfNode_440.material} />
          <mesh geometry={nodes._gltfNode_441.geometry} material={nodes._gltfNode_441.material} />
        </group>
        <mesh geometry={nodes._gltfNode_427.geometry} material={nodes._gltfNode_427.material} />
      </group>
      <group position={[5.108, 5.238, 1.723]} rotation={[0, -Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.408, -67.074, -240.631]} rotation={[1.959, 0.393, -2.388]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_445.geometry} material={nodes._gltfNode_445.material} />
          <mesh geometry={nodes._gltfNode_446.geometry} material={nodes._gltfNode_446.material} />
        </group>
        <group position={[-2.408, -67.074, -96.678]} rotation={[1.69, 0.533, -1.803]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_448.geometry} material={nodes._gltfNode_448.material} />
          <mesh geometry={nodes._gltfNode_449.geometry} material={nodes._gltfNode_449.material} />
        </group>
        <group position={[-2.408, -67.074, 117.125]} rotation={[1.32, 0.49, -1.073]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_451.geometry} material={nodes._gltfNode_451.material} />
          <mesh geometry={nodes._gltfNode_452.geometry} material={nodes._gltfNode_452.material} />
        </group>
        <group position={[-0.921, -67.074, 2.977]} rotation={[1.473, 0.537, -1.381]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_454.geometry} material={nodes._gltfNode_454.material} />
          <mesh geometry={nodes._gltfNode_455.geometry} material={nodes._gltfNode_455.material} />
        </group>
        <group position={[-2.099, -67.074, 255.106]} rotation={[1.784, 0.506, -1.992]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_457.geometry} material={nodes._gltfNode_457.material} />
          <mesh geometry={nodes._gltfNode_458.geometry} material={nodes._gltfNode_458.material} />
        </group>
        <mesh geometry={nodes._gltfNode_444.geometry} material={nodes._gltfNode_444.material} />
      </group>
      <group position={[5.196, 5.352, -8.349]}>
        <group position={[-3.787, -1.042, 0.039]} rotation={[2.088, -0.179, 2.838]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_462.geometry} material={nodes._gltfNode_462.material} />
          <mesh geometry={nodes._gltfNode_463.geometry} material={nodes._gltfNode_463.material} />
        </group>
        <group position={[-0.892, -1.042, 0.027]} rotation={[2.02, 0.319, -2.565]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_465.geometry} material={nodes._gltfNode_465.material} />
          <mesh geometry={nodes._gltfNode_466.geometry} material={nodes._gltfNode_466.material} />
        </group>
        <group position={[-0.333, -1.042, -0.035]} rotation={[1.038, -0.123, 0.206]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_468.geometry} material={nodes._gltfNode_468.material} />
          <mesh geometry={nodes._gltfNode_469.geometry} material={nodes._gltfNode_469.material} />
        </group>
        <group position={[1.313, -1.042, 0.013]} rotation={[1.036, 0.113, -0.188]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_471.geometry} material={nodes._gltfNode_471.material} />
          <mesh geometry={nodes._gltfNode_472.geometry} material={nodes._gltfNode_472.material} />
        </group>
        <group position={[2.77, -1.042, -0.008]} rotation={[1.079, 0.245, -0.425]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_474.geometry} material={nodes._gltfNode_474.material} />
          <mesh geometry={nodes._gltfNode_475.geometry} material={nodes._gltfNode_475.material} />
        </group>
        <mesh geometry={nodes._gltfNode_461.geometry} material={nodes._gltfNode_461.material} />
      </group>
      <group position={[-3.608, 5.352, -8.349]}>
        <group position={[-3.781, -1.042, -0.035]} rotation={[1.098, -0.283, 0.499]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_479.geometry} material={nodes._gltfNode_479.material} />
          <mesh geometry={nodes._gltfNode_480.geometry} material={nodes._gltfNode_480.material} />
        </group>
        <group position={[-1.452, -1.042, 0.019]} rotation={[2.048, -0.274, 2.66]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_482.geometry} material={nodes._gltfNode_482.material} />
          <mesh geometry={nodes._gltfNode_483.geometry} material={nodes._gltfNode_483.material} />
        </group>
        <group position={[-1.816, -1.042, -0.035]} rotation={[1.065, 0.212, -0.363]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_485.geometry} material={nodes._gltfNode_485.material} />
          <mesh geometry={nodes._gltfNode_486.geometry} material={nodes._gltfNode_486.material} />
        </group>
        <group position={[0.446, -1.042, 0.013]} rotation={[2.114, 0.052, -3.055]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_488.geometry} material={nodes._gltfNode_488.material} />
          <mesh geometry={nodes._gltfNode_489.geometry} material={nodes._gltfNode_489.material} />
        </group>
        <group position={[2.521, -1.042, -0.008]} rotation={[2.096, 0.154, -2.882]} scale={[0.128, 0.22, 0.128]}>
          <mesh geometry={nodes._gltfNode_491.geometry} material={nodes._gltfNode_491.material} />
          <mesh geometry={nodes._gltfNode_492.geometry} material={nodes._gltfNode_492.material} />
        </group>
        <mesh geometry={nodes._gltfNode_478.geometry} material={nodes._gltfNode_478.material} />
      </group>
      <group position={[-6.64, 5.536, -12.94]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.281, -88.634, -114.464]} rotation={[1.759, 0.515, -1.94]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_496.geometry} material={nodes._gltfNode_496.material} />
          <mesh geometry={nodes._gltfNode_497.geometry} material={nodes._gltfNode_497.material} />
        </group>
        <group position={[-2.208, -88.634, 116.102]} rotation={[1.299, 0.478, -1.026]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_499.geometry} material={nodes._gltfNode_499.material} />
          <mesh geometry={nodes._gltfNode_500.geometry} material={nodes._gltfNode_500.material} />
        </group>
        <mesh geometry={nodes._gltfNode_495.geometry} material={nodes._gltfNode_495.material} />
      </group>
      <group position={[5.757, 5.536, -12.94]} rotation={[0, Math.PI / 2, 0]} scale={0.014}>
        <group position={[-2.281, -88.634, -114.464]} rotation={[1.759, 0.515, -1.94]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_504.geometry} material={nodes._gltfNode_504.material} />
          <mesh geometry={nodes._gltfNode_505.geometry} material={nodes._gltfNode_505.material} />
        </group>
        <group position={[-2.208, -88.634, 116.102]} rotation={[1.299, 0.478, -1.026]} scale={[9.212, 15.926, 9.212]}>
          <mesh geometry={nodes._gltfNode_507.geometry} material={nodes._gltfNode_507.material} />
          <mesh geometry={nodes._gltfNode_508.geometry} material={nodes._gltfNode_508.material} />
        </group>
        <mesh geometry={nodes._gltfNode_503.geometry} material={nodes._gltfNode_503.material} />
      </group>
      <group position={[5.745, 1.764, -10.385]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_527.geometry} material={nodes._gltfNode_527.material} />
        <mesh geometry={nodes._gltfNode_528.geometry} material={nodes._gltfNode_528.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_530.geometry} material={nodes._gltfNode_530.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[5.745, 1.764, -1.172]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_533.geometry} material={nodes._gltfNode_533.material} />
        <mesh geometry={nodes._gltfNode_534.geometry} material={nodes._gltfNode_534.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_536.geometry} material={nodes._gltfNode_536.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-0.411, 1.764, -1.172]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_539.geometry} material={nodes._gltfNode_539.material} />
        <mesh geometry={nodes._gltfNode_540.geometry} material={nodes._gltfNode_540.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_542.geometry} material={nodes._gltfNode_542.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-6.54, 1.764, -1.172]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_545.geometry} material={nodes._gltfNode_545.material} />
        <mesh geometry={nodes._gltfNode_546.geometry} material={nodes._gltfNode_546.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_548.geometry} material={nodes._gltfNode_548.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-6.54, 1.764, -10.422]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_551.geometry} material={nodes._gltfNode_551.material} />
        <mesh geometry={nodes._gltfNode_552.geometry} material={nodes._gltfNode_552.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_554.geometry} material={nodes._gltfNode_554.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-3.62, 1.764, -5.952]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_557.geometry} material={nodes._gltfNode_557.material} />
        <mesh geometry={nodes._gltfNode_558.geometry} material={nodes._gltfNode_558.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_560.geometry} material={nodes._gltfNode_560.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[2.249, 1.764, -5.952]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes._gltfNode_563.geometry} material={nodes._gltfNode_563.material} />
        <mesh geometry={nodes._gltfNode_564.geometry} material={nodes._gltfNode_564.material} position={[-0.195, 0.345, 0]} scale={0.748} />
        <mesh geometry={nodes._gltfNode_566.geometry} material={nodes._gltfNode_566.material} position={[0.195, 0.345, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.748} />
      </group>
      <group position={[-13.102, 2.652, -12.876]} scale={3.191}>
        <mesh geometry={nodes._gltfNode_569.geometry} material={nodes._gltfNode_569.material} />
        <mesh geometry={nodes._gltfNode_570.geometry} material={nodes._gltfNode_570.material} position={[-0.001, -0.002, -0.047]} />
      </group>
      <group position={[14.588, 2.307, -14.104]} scale={0.141}>
        <mesh geometry={nodes._gltfNode_585.geometry} material={nodes._gltfNode_585.material} />
        <mesh geometry={nodes._gltfNode_586.geometry} material={nodes._gltfNode_586.material} position={[-0.052, 0.043, 0.096]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.363} />
      </group>
      <mesh geometry={nodes._gltfNode_0.geometry} material={nodes._gltfNode_0.material} position={[0.199, 3.874, -5.536]} scale={4.985} />
      <mesh geometry={nodes._gltfNode_2.geometry} material={nodes._gltfNode_2.material} position={[6.26, 3.094, -4.331]} scale={[0.604, 0.923, 1]} />
      <mesh geometry={nodes._gltfNode_4.geometry} material={nodes._gltfNode_4.material} position={[-0.061, 7.918, -4.981]} rotation={[-Math.PI, 0, 0]} scale={[15.339, 15.339, 10.168]} />
      <mesh geometry={nodes._gltfNode_52.geometry} material={nodes._gltfNode_52.material} position={[14.633, 3.867, -5.064]} scale={[0.604, 0.923, 1]} />
      <mesh geometry={nodes._gltfNode_148.geometry} material={nodes._gltfNode_148.material} position={[3.669, 0.036, -14.843]} scale={0.181} />
      <mesh geometry={nodes._gltfNode_150.geometry} material={nodes._gltfNode_150.material} position={[3.13, 0.351, -14.665]} scale={[0.151, 0.214, 0.081]} />
      <mesh geometry={nodes._gltfNode_152.geometry} material={nodes._gltfNode_152.material} position={[-3.013, 1.377, -14.752]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.045} />
      <mesh geometry={nodes._gltfNode_154.geometry} material={nodes._gltfNode_154.material} position={[3.651, 1.045, -14.852]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.067} />
      <mesh geometry={nodes._gltfNode_425.geometry} material={nodes._gltfNode_425.material} position={[0, 0.029, -19.842]} scale={[15.339, 15.339, 10.168]} />
      <mesh geometry={nodes._gltfNode_511.geometry} material={nodes._gltfNode_511.material} position={[-3.514, 0.415, 1.603]} rotation={[-Math.PI, 1.336, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_513.geometry} material={nodes._gltfNode_513.material} position={[6.454, 0.05, -0.975]} />
      <mesh geometry={nodes._gltfNode_515.geometry} material={nodes._gltfNode_515.material} position={[2.821, 0.415, 1.621]} rotation={[-Math.PI, 1.336, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_517.geometry} material={nodes._gltfNode_517.material} position={[-11.402, 0.415, -2.843]} rotation={[-Math.PI, -0.236, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_519.geometry} material={nodes._gltfNode_519.material} position={[-11.498, 0.415, -8.219]} rotation={[-Math.PI, -0.252, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_521.geometry} material={nodes._gltfNode_521.material} position={[10.566, 0.415, 0.495]} rotation={[-Math.PI, -0.394, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_523.geometry} material={nodes._gltfNode_523.material} position={[10.229, 0.415, -5.012]} rotation={[-Math.PI, -0.233, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_525.geometry} material={nodes._gltfNode_525.material} position={[10.342, 0.415, -10.491]} rotation={[-Math.PI, -0.161, -Math.PI]} scale={0.403} />
      <mesh geometry={nodes._gltfNode_573.geometry} material={nodes._gltfNode_573.material} position={[-8.234, 3.272, 4.917]} rotation={[0, Math.PI / 2, 0]} scale={0.904} />
      <mesh geometry={nodes._gltfNode_575.geometry} material={nodes._gltfNode_575.material} position={[-0.006, 3.272, 4.917]} rotation={[0, Math.PI / 2, 0]} scale={0.904} />
      <mesh geometry={nodes._gltfNode_577.geometry} material={nodes._gltfNode_577.material} position={[8.271, 3.272, 4.917]} rotation={[0, Math.PI / 2, 0]} scale={0.904} />
      <mesh geometry={nodes._gltfNode_579.geometry} material={nodes._gltfNode_579.material} position={[3.737, 0.111, -14.843]} rotation={[Math.PI / 2, 0, 0]} scale={[0.071, 0.042, 0.071]} />
      <mesh geometry={nodes._gltfNode_581.geometry} material={nodes._gltfNode_581.material} position={[0, 0.029, -19.842]} scale={[15.339, 15.339, 10.168]} />
      <mesh geometry={nodes._gltfNode_583.geometry} material={nodes._gltfNode_583.material} position={[0.754, 5.67, 0.632]} />
      <mesh geometry={nodes._gltfNode_589.geometry} material={nodes._gltfNode_589.material} position={[14.582, 2.84, 3.771]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes._gltfNode_591.geometry} material={nodes._gltfNode_591.material} position={[14.581, 4.135, -13.996]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes._gltfNode_593.geometry} material={nodes._gltfNode_593.material} position={[14.581, 3.133, -13.927]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes._gltfNode_595.geometry} material={nodes._gltfNode_595.material} position={[14.581, 4.134, 3.95]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.192} />
      <mesh geometry={nodes._gltfNode_597.geometry} material={nodes._gltfNode_597.material} position={[14.58, 5.269, -13.658]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.368} />
      <mesh geometry={nodes._gltfNode_599.geometry} material={nodes._gltfNode_599.material} position={[14.58, 5.269, 3.574]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.368} />
    </group>
  )
}

useGLTF.preload('/tienda.gltf')
